# MySQL to Elasticsearch Replication Configuration (Updated for New Stream System)
# This demonstrates streaming MySQL data to Elasticsearch for search indexing

server:
  host: "0.0.0.0"
  port: 8080
  metrics_port: 9090

logging:
  level: "info"
  format: "json"

# New streams configuration format - SOURCE ONLY
streams:
  - name: "mysql-products-stream"
    enabled: true
    batch_size: 1000
    buffer_size: 10000
    
    # Source configuration (MySQL)
    source:
      type: "mysql"
      host: "mysql-source"
      port: 3306
      database: "source_db"
      username: "replicator"
      password: "password123"
      options:
        table: "products"
        server_id: 100
        binlog_enabled: true

monitoring:
  metrics:
    enabled: true
    path: "/metrics"
  health:
    enabled: true
    path: "/health"
  prometheus:
    enabled: true
    namespace: "replicator"
    subsystem: "mysql_elasticsearch"

# Azure configuration (for future deployment)
azure:
  enabled: false
  
# Global authentication settings
authentication:
  enabled: false